// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjRGPb5DKEc-jzxdLLigvcxeCjFvdrA4',
    appId: '1:795651157079:web:01bbab23d670915ef3c712',
    messagingSenderId: '795651157079',
    projectId: 'fluttergram-fdaa3',
    authDomain: 'fluttergram-fdaa3.firebaseapp.com',
    storageBucket: 'fluttergram-fdaa3.appspot.com',
    measurementId: 'G-S1YW7KT3CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtKEtYUTFErlwXqj7p2d8YubAdrkR-nc',
    appId: '1:795651157079:android:128d938289714839f3c712',
    messagingSenderId: '795651157079',
    projectId: 'fluttergram-fdaa3',
    storageBucket: 'fluttergram-fdaa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBT75amDwzXPxEB0e_MaRZ3jOYAjX9hh0',
    appId: '1:795651157079:ios:2e96fca332112436f3c712',
    messagingSenderId: '795651157079',
    projectId: 'fluttergram-fdaa3',
    storageBucket: 'fluttergram-fdaa3.appspot.com',
    androidClientId: '795651157079-7690mnn5n3ptqojo4hnheb00irsusgbv.apps.googleusercontent.com',
    iosClientId: '795651157079-0a21rq88i5vg2oj6o3544beo9cuui37u.apps.googleusercontent.com',
    iosBundleId: 'com.uzcoding.fluttergram',
  );
}
